
random_state: 42
model_name: "baseline"

# Testing
use_best_models: 1 # True
test_batch_size: 64
use_nfolds: 5

# Training
pretrained: 1 # True
device: "cuda"
nfold: 5
batch_size: 24
n_workers: 6
epochs: 5
weight_decay: 1e-6
max_grad_norm: 1000
lr_max: 4e-4
epochs_warmup: 1.0
model_base_type: "tf_efficientnet_b5_ns"

# Augmentations
augmentaion_train: 1 # True
flip_rate: 0.5
freq_shift_rate: 1.0
time_mask_num: 1
freq_mask_num: 2

# Data generation
num_signals: 10000 
num_noise: 10000