
random_state: 42
model_name: "spectrogram_v2"
processing: "baseline"
dataset: "baseline"

input_size: 128

# Testing
use_best_models: 1 # True
test_batch_size: 128
use_nfolds: 5
score_bust: 0

# Training
pretrained: 1 # True
device: "cuda"
nfold: 5
batch_size: 14
n_workers: 6
epochs: 5
weight_decay: 1.0e-6
max_grad_norm: 1.36
lr_max: 5.6e-4
epochs_warmup: 1.0
dropout: 0.25
once_cycle_pct_start: 0.1
model_base_type: "tf_efficientnet_b7_ns"

# Augmentations
augmentaion_train: 1 # True
flip_rate: 0.5
freq_shift_rate: 1.0
time_mask_num: 3
freq_mask_num: 1

# Data generation
num_signals: 20000
num_noise: 20000
sqrtsxdiv: 30